### ISSUE TITLE
Reboot loop

### ISSUE THREAD

**Issue by sreknob** [konnected-io/konnected-security#60]
So, I just updated my config to do some additional testing and now I'm stuck in a reboot loop as soon as my ESP gets the config information from Home Assistant. Each time it errors with HTTP Call: -1 state 1 pin 7
I'm running a docker of the latest dev branch of Home Assistant (0.70.0.dev0) which has konnected integration.
I had a jumper on D7 to ground during the update but it continues the loop even with nothing connected.
Log shows:
```
Konnected firmware 2.2
NodeMCU 2.2.0.0 build 20180405 powered by Lua 5.1.4 on SDK 2.2.1(cfd48f3)
Heap: 	39856	Initializing Konnected
Heap: 	35312	Version: 	2.2.0
Heap: 	33688	Connecting to Wifi..
> print(uart.setup(0, 15200, 8, 0, 1, 1 ))
115200
> 
Communication with MCU..Got answer! Communication with MCU established.
AutoDetect firmware...

Can't autodetect firmware, because proper answer not received (may be unknown firmware). 
Please, reset module or continue.
 IP: 	192.168.20.199	255.255.255.0	192.168.20.1
Heap: 	37824	UPnP: 	Listening for UPnP discovery
Heap: 	37608	HTTP: 	Starting server at http://192.168.20.199:9664
Heap: 	37432	Loaded: 	server
Heap:	32024	Initializing actuator pin:	1	Trigger:	0
Heap:	31992	Initializing actuator pin:	2	Trigger:	0
Heap:	31992	Initializing actuator pin:	5	Trigger:	0
Heap:	31992	Initializing actuator pin:	6	Trigger:	0
Heap: 	31736	Loaded: 	application
Heap: 	30080	HTTP: 	Status
Heap: 	28304	HTTP: 	Settings
Heap: 	25008	Wrote: 	smartthings.lua
Heap: 	24976	Wrote: 	sensors.lua
Heap: 	24704	Wrote: 	actuators.lua
Settings updated! Restarting in 5 seconds...

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 26212, room 16 
tail 4
chksum 0xfc
load 0x3ffe8000, len 2340, room 4 
tail 0
chksum 0xeb
load 0x3ffe8924, len 136, room 8 
tail 0
chksum 0x2b
csum 0x2b

Konnected firmware 2.2
NodeMCU 2.2.0.0 build 20180405 powered by Lua 5.1.4 on SDK 2.2.1(cfd48f3)
Heap: 	39856	Initializing Konnected
Heap: 	35312	Version: 	2.2.0
Heap: 	33688	Connecting to Wifi..
> Heap: 	37536	Wifi connected with IP: 	192.168.20.199	255.255.255.0	192.168.20.1
Heap: 	37504	UPnP: 	Listening for UPnP discovery
Heap: 	37288	HTTP: 	Starting server at http://192.168.20.199:9664
Heap: 	37112	Loaded: 	server
Heap:	32128	Initializing sensor pin:	7
Heap:	32096	Initializing actuator pin:	1	Trigger:	0
Heap:	32096	Initializing actuator pin:	2	Trigger:	0
Heap:	32096	Initializing actuator pin:	5	Trigger:	0
Heap:	32096	Initializing actuator pin:	6	Trigger:	0
Heap: 	31848	Loaded: 	application
Heap: 	32488	Responded to UPnP Discovery request from 192.168.20.18:38442
Heap: 	31968	Responded to UPnP Discovery request from 192.168.20.5:56672
Heap: 	25528	HTTP: 	Discovery
HTTP client: Connection timeout
Heap:	35248	HTTP Call:	-1	state	1	pin	7

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 26212, room 16 
tail 4
chksum 0xfc
load 0x3ffe8000, len 2340, room 4 
tail 0
chksum 0xeb
load 0x3ffe8924, len 136, room 8 
tail 0
chksum 0x2b
csum 0x2b
```
My config for this unit is:
```
  # Test Module
  - id: 1964f1
    binary_sensors:
      - pin: 7
        type: door
        name: 'Konnected Test Door'
    switches:
      - pin: 1
        name: 'Konnected Test Relay 1'
        activation: low
      - pin: 2
        name: 'Konnected Test Relay 2'
        activation: low
      - pin: 5
        name: 'Konnected Test Relay 3'
        activation: low
      - pin: 6
        name: 'Konnected Test Relay 4'
        activation: low

```
