### ISSUE TITLE
Home assistant continuous warning beep issue

### ISSUE THREAD

**Issue by srk23** [konnected-io/konnected-security#81]
I can get an intermittent beep with  3.3v piezo buzzer using the following in Home Assistant:
```     
    switches: 
       - pin: 8
          name: 'Warning buzzer'
          momentary: 500
          pause: 500
          repeat: 15
```
However, if I want a continuous beep which stays on until switched off, the following code from the documentation does not work as expected:
```
      switches: 
        - pin: 8
          name: 'Warning buzzer'
          momentary: 500
          pause: 500
          repeat: -1
```
The '-1' switch results in the piezo sounding once and then switcihing off in HA - my understanding from the documentation is that it should continue to sound until switched off?

I am using HA 0.85.0, with Konnected firmware 2.0.5, software 2.1.3.
