### ISSUE TITLE
MQTT support?

### ISSUE THREAD

**Issue by podarok** [konnected-io/konnected-security#99]
Hi.
Thank you for the device. Received recently and replaced Integra64 .
I see that devices are sending information to Hubitat every time there is a change in sensors.
Is there a plan to add MQTT support?
Would be cool to use this protocol. It would be easier to add monitoring later

**Comment by heythisisnate** [comment]
Yes, MQTT support is on the near-term roadmap.

**Comment by Korte68** [comment]
great...any estimation?

**Comment by lipigab** [comment]
That's the only thing while I haven't pulled the trigger yet...

**Comment by nzbullet** [comment]
Any update on when this will be available? I’m a Homebridge user and don’t user any of the current integration options (and not do I intend to) so like others not having MQTT it is the only thing that stops me buying.

**Comment by Korte68** [comment]
> Yes, MQTT support is on the near-term roadmap.

we have different meaning on 'near-term roadmap'....

**Comment by mkormendy** [comment]
@heythisisnate,... any updates?

**Comment by nzbullet** [comment]
Any updates on this 'near-term' roadmap item?

**Comment by heythisisnate** [comment]
Ah yeah, this has definitely been pushed out longer than I originally expected. Priorities shift.

I'm still considering adding MQTT support to the Konnected firmware, but also recommending ESPHome as an alternative firmware that already supports it well. All Konnected hardware will run ESPHome. You can find a zone to NodeMCU pin mapping here: https://help.konnected.io/support/solutions/articles/32000026808-pin-mapping

Then, use the NodeMCU platform in your ESPHome configuration. An example config may look like this:

```
esphome:
  name: konnected-1
  platform: ESP8266
  board: nodemcuv2

mqtt:
  broker: 10.0.0.2
  username: heythisisnate
  password: MyMQTTPassword

binary_sensor:
  - platform: gpio
    name: "Front Door"
    pin: D1
  - platform: gpio
    name: "Patio Door"
    pin: 
      number: D2
      mode: INPUT_PULLUP
  - platform: gpio
    name: "Living Room Motion"
    pin:
      number: D5
      mode: INPUT_PULLUP
    device_class: motion

switch:
  - platform: gpio
    pin: D8
    name: "Siren"
```

Please let me know if the ESPHome approach would meet your needs. I'm interested in your use cases for MQTT support. It's not a popular feature request, but a few really want it.
